# Generated by Django 5.2.6 on 2025-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('licencia', models.CharField(max_length=20)),
            ],
        ),
    ]
