# Generated by Django 5.2.6 on 2025-10-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
    ]
