# Generated by Django 5.2.6 on 2025-10-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='hora_salida',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='capacidad',
        ),
    ]
