# Generated by Django 5.2.7 on 2025-10-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='reserva',
            name='identificacion',
            field=models.CharField(default='SinID', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='isben',
            field=models.CharField(default='SinSisben', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='SinNombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='programa',
            field=models.CharField(default='SinPrograma', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
