# Generated by Django 5.2.7 on 2025-10-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_remove_reserva_estudiante_reserva_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='cupos_disponibles',
        ),
        migrations.AddField(
            model_name='ruta',
            name='capacidad',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(choices=[('Centro_Coquivacoa', 'Centro - Coquivacoa'), ('Majayura', 'Majayura'), ('Marbella', 'Marbella'), ('La20', 'La 20'), ('15deMayo', '15 de Mayo'), ('27_37', '27-37'), ('15Derecho', '15 Derecho'), ('Dividivi', 'Dividivi'), ('RoundPoint', 'Round Point')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutas.ruta')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
